name: Build Armbian x86_UEFI

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检查出 Armbian 源码
        uses: actions/checkout@v4
        with:
          repository: armbian/build  # 官方 Armbian 源码仓库
          ref: main  # 拉取最新的 main 分支

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y git curl jq xz-utils rsync
          sudo apt install -y python3 python3-pip
          sudo apt install -y gcc make flex bison bc libssl-dev

      - name: 开始编译 Armbian x86 UEFI 固件
        run: |
            ./compile.sh \
            BOARD=x86 \
            BRANCH=current \
            RELEASE=bookworm \
            BUILD_MINIMAL=no \
            BUILD_DESKTOP=no \
            KERNEL_CONFIGURE=no

      - name: 上传编译好的固件
        uses: actions/upload-artifact@v4
        with:
          name: armbian-x86-uefi
          path: output/images/*.img
